parameters:
#    izze_security.example.class: Izze\SecurityBundle\Example

services:
#    izze_security.example:
#        class: %izze_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
