parameters:
#    izze_hoo.example.class: Izze\HooBundle\Example

services:
#    izze_hoo.example:
#        class: %izze_hoo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
